# Generated by Django 4.2.16 on 2024-11-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
