# Generated by Django 4.2.16 on 2024-11-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hire', '0002_expertimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hire.ourexperts')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expert_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
